//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHaiSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public string MaMenu { get; set; }
        public string TenMenu { get; set; }
        public string LinkMenu { get; set; }
        public string CapMenu { get; set; }
        public string ThuTuMenu { get; set; }
        public string LoaiMenu { get; set; }
        public string MaMenuCha { get; set; }
        public string LinkMenuCha { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
